import contentCollections from "@content-collections/vite";
import { defineConfig } from "vite";
import { devtools } from "@tanstack/devtools-vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import viteTsConfigPaths from "vite-tsconfig-paths";
import stylex from "@stylexjs/unplugin";
import { cloudflare } from "@cloudflare/vite-plugin";

const config = defineConfig(({ mode }) => {
  const isTest = mode === "test" || process.env.VITEST === "true";

  return {
    plugins: [
      devtools(),
      isTest ? null : cloudflare({ viteEnvironment: { name: "ssr" } }),
      // this is the plugin that enables path aliases
      viteTsConfigPaths({
        projects: ["./tsconfig.json"],
      }),
      stylex.vite({ devMode: isTest ? "off" : "full" }),
      tanstackStart({
        // Every page is rendered to HTML at build time (content only changes on
        // deploy) and served as a static asset: no Worker CPU or request per view.
        prerender: {
          enabled: true,
          crawlLinks: true,
          // "/food/ann-arbor" -> food/ann-arbor.html, which Cloudflare serves at the
          // slash-less URL; a folder index would redirect to "/food/ann-arbor/".
          autoSubfolderIndex: false,
          failOnError: true,
          // Filtered views (?min=9) share their page's HTML, so skip them (they'd
          // overwrite it); files like /hops-report.pdf are already static.
          filter: ({ path }) => !/[?#]/.test(path) && !/\.[a-z0-9]+$/i.test(path),
        },
        // public/sitemap.xml is generated by scripts/generate-seo-files.mjs.
        sitemap: { enabled: false },
      }),
      viteReact(),
      isTest ? null : contentCollections(),
    ].filter(Boolean),
  };
});

export default config;
